'use strict';function p(e,d,f,m){e.f.ca(e.F,d,f,m,void 0)}function w(e,d,f,m){e.f.l?p(e,d,f,m):e.f.ob()._OnMessageFromDOM({type:"event",component:e.F,handler:d,dispatchOpts:m||null,data:f,responseId:null})}function E(e,d,f){e.f.a(e.F,d,f)}function F(e,d){for(const [f,m]of d)E(e,f,m)}window.N=class{constructor(e,d){this.f=e;this.F=d}xa(){}};
window.cb=class{constructor(e,d){this.Ra=e;this.Tb=d;this.A=-1;this.X=-Infinity;this.Yb=()=>{this.A=-1;this.X=Date.now();this.G=!0;this.Ra();this.G=!1};this.Sa=this.G=!1}};"use strict";function G(e,d){const f=d.elementId,m=e.Aa(d);e.h.set(f,m);d.isVisible||(m.style.display="none");m.addEventListener("focus",()=>{H(e,"elem-focused",f)});m.addEventListener("blur",()=>{H(e,"elem-blurred",f)});e.U&&document.body.appendChild(m)}function I(e,d,f){E(e,d,m=>{const t=e.h.get(m.elementId);return f(t,m)})}
function H(e,d,f){var m;m||(m={});m.elementId=f;p(e,d,m)}
window.$a=class extends self.N{constructor(e,d){super(e,d);this.h=new Map;this.U=!0;F(this,[["create",f=>G(this,f)],["destroy",f=>{{f=f.elementId;const m=this.h.get(f);this.Ba(m);this.U&&m.parentElement.removeChild(m);this.h.delete(f)}}],["set-visible",f=>{this.U&&(this.h.get(f.elementId).style.display=f.isVisible?"":"none")}],["update-position",f=>{if(this.U){var m=this.h.get(f.elementId);m.style.left=f.left+"px";m.style.top=f.top+"px";m.style.width=f.width+"px";m.style.height=f.height+"px";f=f.fontSize;
null!==f&&(m.style.fontSize=f+"em")}}],["update-state",f=>{this.h.get(f.elementId);this.Ea()}],["focus",f=>this.la(f)],["set-css-style",f=>{this.h.get(f.elementId).style[f.prop]=f.val}],["set-attribute",f=>{this.h.get(f.elementId).setAttribute(f.name,f.val)}],["remove-attribute",f=>{this.h.get(f.elementId).removeAttribute(f.name)}]]);I(this,"get-element",f=>f)}Aa(){throw Error("required override");}Ba(){}Ea(){throw Error("required override");}la(e){var d=this.h.get(e.elementId);e.focus?d.focus():
d.blur()}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function d(q){if(q.ac){const c=document.createElement("script");c.async=!1;c.textContent=q.dc;document.head.appendChild(c)}else return new Promise((c,g)=>{const a=document.createElement("script");a.onload=c;a.onerror=g;a.async=!1;a.src=q;document.head.appendChild(a)})}let f=new Audio;const m={"audio/webm; codecs=opus":!!f.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!f.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!f.canPlayType("audio/webm; codecs=vorbis"),
"audio/ogg; codecs=vorbis":!!f.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!f.canPlayType("audio/mp4"),"audio/mpeg":!!f.canPlayType("audio/mpeg")};f=null;async function t(q){q=await A(q);return(new TextDecoder("utf-8")).decode(q)}function A(q){return new Promise((c,g)=>{const a=new FileReader;a.onload=b=>c(b.target.result);a.onerror=b=>g(b);a.readAsArrayBuffer(q)})}const x=[];let v=0;window.RealFile=window.File;const u=[],y=new Map,z=new Map;let B=0;const D=[];self.qc=function(q){if("function"!==
typeof q)throw Error("runOnStartup called without a function");D.push(q)};const r=new Set(["cordova","playable-ad","instant-games"]);window.C=class q{constructor(c){this.l=c.fc;this.I=null;this.c="";this.$=c.cc;this.L={};this.j=this.ra=this.Wa=null;this.V=[];this.H=this.g=this.ua=null;this.u=-1;this.Xb=()=>this.Hb();this.Va=[];this.b=c.Xa;!this.l||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.l=!1);r.has(this.b)&&this.l&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.l=!1);this.Y=this.i=null;"html5"!==this.b&&"playable-ad"!==this.b||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",g=>this.ub(g));this.a("runtime","create-job-worker",()=>this.vb());"cordova"===this.b?document.addEventListener("deviceready",()=>this.Ha(c)):this.Ha(c)}Ca(){return e&&"cordova"===this.b}O(){return e&&
r.has(this.b)||navigator.standalone}async Ha(c){"preview"===this.b&&(this.j=document.createElement("div"),this.j.className="previewLoadingMessage",this.j.textContent=c.oc,document.body.appendChild(this.j));if("playable-ad"===this.b){this.i=self.c3_base64files;this.Y={};await this.jb();for(let a=0,b=c.B.length;a<b;++a){var g=c.B[a].toLowerCase();this.Y.hasOwnProperty(g)?c.B[a]={ac:!0,dc:this.Y[g]}:this.i.hasOwnProperty(g)&&(c.B[a]=URL.createObjectURL(this.i[g]))}}c.Zb?this.c=c.Zb:(g=location.origin,
this.c=("null"===g?"file:///":g)+location.pathname,g=this.c.lastIndexOf("/"),-1!==g&&(this.c=this.c.substr(0,g+1)));if(c.ic)for(const [a,b]of Object.entries(c.ic))this.L[a]=URL.createObjectURL(b);g=new MessageChannel;this.I=g.port1;this.I.onmessage=a=>this._OnMessageFromRuntime(a.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(a=>this.Eb(a));this.H=new self.ab(this);await J(this.H);this.Da();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&
window.AndroidFullScreen.immersiveMode();this.l?await this.qb(c,g.port2):await this.pb(c,g.port2)}ea(c){return this.L.hasOwnProperty(c)?this.L[c]:c.endsWith("/workermain.js")&&this.L.hasOwnProperty("workermain.js")?this.L["workermain.js"]:"playable-ad"===this.b&&this.i.hasOwnProperty(c.toLowerCase())?URL.createObjectURL(this.i[c.toLowerCase()]):c}async aa(c,g,a){if(c.startsWith("blob:"))return new Worker(c,a);if(this.Ca()&&"file:"===location.protocol)return c=await this.za(this.$+c),new Worker(URL.createObjectURL(new Blob([c],
{type:"application/javascript"})),a);c=new URL(c,g);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");c=await c.blob();return new Worker(URL.createObjectURL(c),a)}return new Worker(c,a)}o(){return Math.max(window.innerWidth,1)}m(){return Math.max(window.innerHeight,1)}Da(){if(this.O()){const c=document.documentElement.style,g=document.body.style,a=window.innerWidth<window.innerHeight,b=a?window.screen.width:window.screen.height;g.height=c.height=
(a?window.screen.height:window.screen.width)+"px";g.width=c.width=b+"px"}}Ga(c){var g=this.H;return{baseUrl:this.c,windowInnerWidth:this.o(),windowInnerHeight:this.m(),devicePixelRatio:window.devicePixelRatio,isFullscreen:q.ba(),projectData:c.pc,previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:c.Xa,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.nc,jobScheduler:{inputPort:g.pa,outputPort:g.ta,maxNumWorkers:g.Vb},
supportedAudioFormats:m,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$+"opus.wasm.wasm",isiOSCordova:this.Ca(),isiOSWebView:this.O(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async qb(c,g){var a=this.ea(c.hc);this.Wa=await this.aa(a,this.c,{name:"Runtime"});this.g=document.createElement("canvas");this.g.style.display="none";a=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=
this.g;this.Wa.postMessage(Object.assign(this.Ga(c),{type:"init-runtime",isInWorker:!0,messagePort:g,canvas:a,workerDependencyScripts:c.wa||[],engineScripts:c.B,projectScripts:window.mc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[g,a,...K(this.H)]);this.V=u.map(b=>new b(this));this.Fa();self.c3_callFunction=(b,h)=>this.ua.rb(b,h);"preview"===this.b&&(self.goToLastErrorScript=()=>this.ca("runtime","go-to-last-error-script"))}async pb(c,g){this.g=document.createElement("canvas");this.g.style.display=
"none";document.body.appendChild(this.g);window.c3canvas=this.g;this.V=u.map(b=>new b(this));this.Fa();const a=c.B.map(b=>"string"===typeof b?(new URL(b,this.c)).toString():b);Array.isArray(c.wa)&&a.unshift(...c.wa);await Promise.all(a.map(b=>d(b)));if(c.Ya&&0<c.Ya.length){const b=self.C3_ProjectScriptsStatus;try{if(await Promise.all(c.Ya.map(h=>d(h[1]))),Object.values(b).some(h=>!h)){self.setTimeout(()=>this.Na(b),100);return}}catch(h){console.error("[Preview] Error loading project scripts: ",h);
self.setTimeout(()=>this.Na(b),100);return}}"preview"===this.b&&"object"!==typeof self.jc.kc?(this.T(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.Ga(c),{isInWorker:!1,messagePort:g,canvas:this.g,runOnStartupFunctions:D}),this.Ja(),this.ra=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.ra,
c))}Na(c){this.T();c=`Failed to load project script '${Object.entries(c).filter(g=>!g[1]).map(g=>g[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+c);alert(c)}Ja(){this.T()}T(){this.j&&(this.j.parentElement.removeChild(this.j),this.j=null)}async vb(){const c=await L(this.H);return{outputPort:c,transferables:[c]}}ob(){if(this.l)throw Error("not available in worker mode");return this.ra}ca(c,g,a,b,h){this.I.postMessage({type:"event",component:c,handler:g,dispatchOpts:b||
null,data:a,responseId:null},h)}bb(c,g){const a=B++,b=new Promise((h,k)=>{z.set(a,{resolve:h,reject:k})});this.I.postMessage({type:"event",component:c,handler:"js-invoke-function",dispatchOpts:null,data:g,responseId:a},void 0);return b}["_OnMessageFromRuntime"](c){const g=c.type;if("event"===g)return this.Ab(c);if("result"===g)this.Kb(c);else if("runtime-ready"===g)this.Lb();else if("alert-error"===g)this.T(),alert(c.message);else if("creating-runtime"===g)this.Ja();else throw Error(`unknown message '${g}'`);
}Ab(c){const g=c.component,a=c.handler,b=c.data,h=c.responseId;if(c=y.get(g))if(c=c.get(a)){var k=null;try{k=c(b)}catch(l){console.error(`Exception in '${g}' handler '${a}':`,l);null!==h&&this.R(h,!1,""+l);return}if(null===h)return k;k&&k.then?k.then(l=>this.R(h,!0,l)).catch(l=>{console.error(`Rejection from '${g}' handler '${a}':`,l);this.R(h,!1,""+l)}):this.R(h,!0,k)}else console.warn(`[DOM] No handler '${a}' for component '${g}'`);else console.warn(`[DOM] No event handlers for component '${g}'`)}R(c,
g,a){let b;a&&a.transferables&&(b=a.transferables);this.I.postMessage({type:"result",responseId:c,isOk:g,result:a},b)}Kb(c){const g=c.responseId,a=c.isOk;c=c.result;const b=z.get(g);a?b.resolve(c):b.reject(c);z.delete(g)}a(c,g,a){let b=y.get(c);b||(b=new Map,y.set(c,b));if(b.has(g))throw Error(`[DOM] Component '${c}' already has handler '${g}'`);b.set(g,a)}static M(c){if(u.includes(c))throw Error("DOM handler already added");u.push(c)}Fa(){for(const c of this.V)if("runtime"===c.F){this.ua=c;return}throw Error("cannot find runtime DOM handler");
}Eb(c){this.ca("debugger","message",c)}Lb(){for(const c of this.V)c.xa()}static ba(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Oa(){-1===this.u&&this.Va.length&&(this.u=requestAnimationFrame(this.Xb))}hb(){-1!==this.u&&(cancelAnimationFrame(this.u),this.u=-1)}Hb(){this.u=-1;for(const c of this.Va)c();this.Oa()}na(){this.ua.na()}async ub(c){const g=c.filename;switch(c.as){case "text":return await this.Za(g);case "buffer":return await this.za(g);
default:throw Error("unsupported type");}}ya(c){const g=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((a,b)=>{window.resolveLocalFileSystemURL(g,h=>{h.file(a,b)},b)})}async Za(c){c=await this.ya(c);return await t(c)}da(){if(x.length&&!(8<=v)){v++;var c=x.shift();this.kb(c.filename,c.ec,c.$b)}}za(c){return new Promise((g,a)=>{x.push({filename:c,ec:b=>{v--;this.da();g(b)},$b:b=>{v--;this.da();a(b)}});this.da()})}async kb(c,g,a){try{const b=await this.ya(c),h=await A(b);
g(h)}catch(b){a(b)}}async jb(){const c=[];for(const [g,a]of Object.entries(this.i))c.push(this.ib(g,a));await Promise.all(c)}async ib(c,g){if("object"===typeof g)this.i[c]=new Blob([g.str],{type:g.type}),this.Y[c]=g.str;else{let a=await this.nb(g);a||(a=this.lb(g));this.i[c]=a}}async nb(c){try{return await (await fetch(c)).blob()}catch(g){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
g),null}}lb(c){c=this.Pb(c);return this.gb(c.data,c.bc)}Pb(c){var g=c.indexOf(",");if(0>g)throw new URIError("expected comma in data: uri");var a=c.substring(g+1);g=c.substring(5,g).split(";");c=g[0]||"";const b=g[2];a="base64"===g[1]||"base64"===b?atob(a):decodeURIComponent(a);return{bc:c,data:a}}gb(c,g){var a=c.length;let b=a>>2,h=new Uint8Array(a),k=new Uint32Array(h.buffer,0,b),l,n;for(n=l=0;l<b;++l)k[l]=c.charCodeAt(n++)|c.charCodeAt(n++)<<8|c.charCodeAt(n++)<<16|c.charCodeAt(n++)<<24;for(a&=
3;a--;)h[n]=c.charCodeAt(n),++n;return new Blob([h],{type:g})}}}"use strict";
{const e=self.C;function d(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents}const f=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),m={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},t={dispatchUserScriptEvent:!0},A={dispatchRuntimeEvent:!0};function x(a){return new Promise((b,h)=>{const k=document.createElement("link");k.onload=()=>b(k);k.onerror=l=>h(l);k.rel=
"stylesheet";k.href=a;document.head.appendChild(k)})}function v(a){return new Promise((b,h)=>{const k=new Image;k.onload=()=>b(k);k.onerror=l=>h(l);k.src=a})}async function u(a){a=URL.createObjectURL(a);try{return await v(a)}finally{URL.revokeObjectURL(a)}}function y(a){return new Promise((b,h)=>{let k=new FileReader;k.onload=l=>b(l.target.result);k.onerror=l=>h(l);k.readAsText(a)})}async function z(a,b,h){if(!/firefox/i.test(navigator.userAgent))return await u(a);var k=await y(a);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),P=l.getAttribute("height");if(!n.includes("%")&&!P.includes("%"))return await u(a)}l.setAttribute("width",b+"px");l.setAttribute("height",h+"px");k=(new XMLSerializer).serializeToString(k);a=new Blob([k],{type:"image/svg+xml"});return await u(a)}function B(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1}const D=new Set(["canvas",
"body","html"]);function r(a){D.has(a.target.tagName.toLowerCase())&&a.preventDefault()}function q(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()}self.C3_GetSvgImageSize=async function(a){a=await u(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();document.body.removeChild(a);return[b.width,b.height]}};self.C3_RasterSvgImageBlob=async function(a,
b,h,k,l){a=await z(a,b,h);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(a,0,0,b,h);return n};let c=!1;document.addEventListener("pause",()=>c=!0);document.addEventListener("resume",()=>c=!1);function g(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}}e.M(class extends self.N{constructor(a){super(a,"runtime");this.Ta=!0;this.v=-1;this.va="any";this.Pa=this.Qa=!1;this.qa=this.K=this.s=null;a.a("canvas","update-size",k=>this.Nb(k));
a.a("runtime","invoke-download",k=>this.Db(k));a.a("runtime","raster-svg-image",k=>this.Ib(k));a.a("runtime","get-svg-image-size",k=>this.Bb(k));a.a("runtime","set-target-orientation",k=>this.Mb(k));a.a("runtime","register-sw",()=>this.Jb());a.a("runtime","post-to-debugger",k=>this.La(k));a.a("runtime","go-to-script",k=>this.La(k));a.a("runtime","before-start-ticking",()=>this.tb());a.a("runtime","debug-highlight",k=>this.wb(k));a.a("runtime","enable-device-orientation",()=>this.fb());a.a("runtime",
"enable-device-motion",()=>this.eb());a.a("runtime","add-stylesheet",k=>this.sb(k));a.a("runtime","alert",k=>this.ga(k));a.a("runtime","hide-cordova-splash",()=>this.Cb());const b=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;b.has(l.tagName.toLowerCase())||B(l)||k.preventDefault()});const h=a.g;window.addEventListener("selectstart",r);window.addEventListener("gesturehold",r);h.addEventListener("selectstart",r);h.addEventListener("gesturehold",
r);window.addEventListener("touchstart",r,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",r,{passive:!1}),h.addEventListener("pointerdown",r)):h.addEventListener("touchstart",r);this.J=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",q,{passive:!1});window.addEventListener("wheel",q,{passive:!1});window.addEventListener("resize",()=>this.Ob());a.O()&&window.addEventListener("focusout",()=>{{const n=
document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):B(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});this.sa=new Set;this.Wb=new WeakSet;this.Ub=!1}tb(){"cordova"===this.f.b?(document.addEventListener("pause",()=>this.ma(!0)),document.addEventListener("resume",()=>this.ma(!1))):document.addEventListener("visibilitychange",()=>this.ma(document.hidden));
return{isSuspended:!(!document.hidden&&!c)}}xa(){window.addEventListener("focus",()=>this.S("window-focus"));window.addEventListener("blur",()=>{this.S("window-blur",{parentHasFocus:g()});this.J=0});window.addEventListener("fullscreenchange",()=>this.ha());window.addEventListener("webkitfullscreenchange",()=>this.ha());window.addEventListener("mozfullscreenchange",()=>this.ha());window.addEventListener("fullscreenerror",b=>this.ia(b));window.addEventListener("webkitfullscreenerror",b=>this.ia(b));
window.addEventListener("mozfullscreenerror",b=>this.ia(b));window.addEventListener("keydown",b=>this.Ka("keydown",b));window.addEventListener("keyup",b=>this.Ka("keyup",b));window.addEventListener("dblclick",b=>this.ja("dblclick",b,m));window.addEventListener("wheel",b=>this.Fb(b));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",b=>{this.fa(b);this.D("pointerdown",b)}),this.f.l&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.K=new self.cb(()=>this.mb(),
5),this.K.Sa=!0,window.addEventListener("pointerrawupdate",b=>this.Gb(b))):window.addEventListener("pointermove",b=>this.D("pointermove",b)),window.addEventListener("pointerup",b=>this.D("pointerup",b)),window.addEventListener("pointercancel",b=>this.D("pointercancel",b))):(window.addEventListener("mousedown",b=>{this.fa(b);this.ka("pointerdown",b)}),window.addEventListener("mousemove",b=>this.ka("pointermove",b)),window.addEventListener("mouseup",b=>this.ka("pointerup",b)),window.addEventListener("touchstart",
b=>{this.fa(b);this.P("pointerdown",b)}),window.addEventListener("touchmove",b=>this.P("pointermove",b)),window.addEventListener("touchend",b=>this.P("pointerup",b)),window.addEventListener("touchcancel",b=>this.P("pointercancel",b)));const a=()=>this.na();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}S(a,b){p(this,a,b||null,A)}o(){return this.f.o()}m(){return this.f.m()}Ob(){const a=
this.o(),b=this.m();this.S("window-resize",{innerWidth:a,innerHeight:b,devicePixelRatio:window.devicePixelRatio});this.f.O()&&(-1!==this.v&&clearTimeout(this.v),this.Ma(a,b,0))}Qb(a,b,h){-1!==this.v&&clearTimeout(this.v);this.v=setTimeout(()=>this.Ma(a,b,h),48)}Ma(a,b,h){const k=this.o(),l=this.m();this.v=-1;k!=a||l!=b?this.S("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>h&&this.Qb(k,l,h+1)}Mb(a){this.va=a.targetOrientation}Rb(){const a=this.va;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(a).catch(b=>console.warn("[Construct 3] Failed to lock orientation: ",b));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));b||console.warn("[Construct 3] Failed to lock orientation")}catch(b){console.warn("[Construct 3] Failed to lock orientation: ",b)}}ha(){const a=
e.ba();a&&"any"!==this.va&&this.Rb();p(this,"fullscreenchange",{isFullscreen:a,innerWidth:this.o(),innerHeight:this.m()})}ia(a){console.warn("[Construct 3] Fullscreen request failed: ",a);p(this,"fullscreenerror",{isFullscreen:e.ba(),innerWidth:this.o(),innerHeight:this.m()})}ma(a){a?this.f.hb():this.f.Oa();p(this,"visibilitychange",{hidden:a})}Ka(a,b){"Backspace"===b.key&&r(b);const h=f.get(b.code)||b.code;w(this,a,{code:h,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,
metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},m)}Fb(a){p(this,"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},m)}ja(a,b,h){d(b)||w(this,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,timeStamp:b.timeStamp},h)}ka(a,b){if(!d(b)){var h=this.J;"pointerdown"===a&&0!==h?a="pointermove":"pointerup"===a&&0!==b.buttons&&(a=
"pointermove");w(this,a,{pointerId:1,pointerType:"mouse",button:b.button,buttons:b.buttons,lastButtons:h,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:b.timeStamp},m);this.J=b.buttons;this.ja(b.type,b,t)}}D(a,b){if(this.K&&"pointermove"!==a){var h=this.K;h.G||(-1!==h.A&&(self.clearTimeout(h.A),h.A=-1),h.X=Date.now())}h=0;"mouse"===b.pointerType&&(h=this.J);w(this,a,{pointerId:b.pointerId,pointerType:b.pointerType,
button:b.button,buttons:b.buttons,lastButtons:h,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},m);"mouse"===b.pointerType&&(h="mousemove","pointerdown"===a?h="mousedown":"pointerup"===a&&(h="pointerup"),this.ja(h,b,t),this.J=b.buttons)}Gb(a){this.qa=a;a=this.K;if(-1===a.A){var b=Date.now(),h=b-a.X,k=a.Tb;h>=
k&&a.Sa?(a.X=b,a.G=!0,a.Ra(),a.G=!1):a.A=self.setTimeout(a.Yb,Math.max(k-h,4))}}mb(){this.D("pointermove",this.qa);this.qa=null}P(a,b){for(let h=0,k=b.changedTouches.length;h<k;++h){const l=b.changedTouches[h];w(this,a,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,
tiltY:0,twist:l.rotationAngle||0,timeStamp:b.timeStamp},m)}}fa(a){window!==window.top&&window.focus();this.Ia(a.target)&&document.activeElement&&!this.Ia(document.activeElement)&&document.activeElement.blur()}Ia(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}fb(){this.Qa||(this.Qa=!0,window.addEventListener("deviceorientation",a=>this.yb(a)),window.addEventListener("deviceorientationabsolute",a=>this.zb(a)))}eb(){this.Pa||(this.Pa=!0,window.addEventListener("devicemotion",
a=>this.xb(a)))}yb(a){p(this,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},m)}zb(a){p(this,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},m)}xb(a){let b=null;var h=a.acceleration;h&&(b={x:h.x||0,y:h.y||0,z:h.z||0});h=null;var k=a.accelerationIncludingGravity;k&&(h={x:k.x||
0,y:k.y||0,z:k.z||0});k=null;const l=a.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});p(this,"devicemotion",{acceleration:b,accelerationIncludingGravity:h,rotationRate:k,interval:a.interval,timeStamp:a.timeStamp},m)}Nb(a){const b=this.f,h=b.g;h.style.width=a.styleWidth+"px";h.style.height=a.styleHeight+"px";h.style.marginLeft=a.marginLeft+"px";h.style.marginTop=a.marginTop+"px";b.Da();this.Ta&&(h.style.display="",this.Ta=!1)}Db(a){const b=a.url;a=a.filename;const h=document.createElement("a"),
k=document.body;h.textContent=a;h.href=b;h.download=a;k.appendChild(h);h.click();k.removeChild(h)}async Ib(a){var b=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async Bb(a){return await self.C3_GetSvgImageSize(a.blob)}async sb(a){await x(a.url)}na(){var a=[...this.sa];this.sa.clear();if(!this.Ub)for(const b of a)(a=b.play())&&
a.catch(()=>{this.Wb.has(b)||this.sa.add(b)})}Cb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}wb(a){if(a.show){this.s||(this.s=document.createElement("div"),this.s.id="inspectOutline",document.body.appendChild(this.s));var b=this.s;b.style.display="";b.style.left=a.left-1+"px";b.style.top=a.top-1+"px";b.style.width=a.width+2+"px";b.style.height=a.height+2+"px";b.textContent=a.name}else this.s&&(this.s.style.display="none")}Jb(){window.C3_RegisterSW&&window.C3_RegisterSW()}La(a){window.c3_postToMessagePort&&
(a.from="runtime",window.c3_postToMessagePort(a))}rb(a,b){return this.f.bb(this.F,{name:a,params:b})}ga(a){alert(a.message)}})}"use strict";async function J(e){if(e.Sb)throw Error("already initialised");e.Sb=!0;var d=e.Z.ea("dispatchworker.js");e.oa=await e.Z.aa(d,e.c,{name:"DispatchWorker"});d=new MessageChannel;e.pa=d.port1;e.oa.postMessage({type:"_init","in-port":d.port2},[d.port2]);e.ta=await L(e)}function K(e){return[e.pa,e.ta]}
async function L(e){const d=e.Ua.length;var f=e.Z.ea("jobworker.js");f=await e.Z.aa(f,e.c,{name:"JobWorker"+d});const m=new MessageChannel,t=new MessageChannel;e.oa.postMessage({type:"_addJobWorker",port:m.port1},[m.port1]);f.postMessage({type:"init",number:d,"dispatch-port":m.port2,"output-port":t.port2},[m.port2,t.port2]);e.Ua.push(f);return t.port1}
self.ab=class{constructor(e){this.Z=e;this.c=e.c;this.c="preview"===e.b?this.c+"c3/workers/":this.c+e.$;this.Vb=Math.min(navigator.hardwareConcurrency||2,16);this.oa=null;this.Ua=[];this.ta=this.pa=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.C({fc:!0,hc:"workermain.js",B:["scripts/c3runtime.js"],cc:"scripts/",wa:[],Xa:"html5"}));"use strict";
async function M(e,d){d=d.type;let f=!0;0===d?f=await O():1===d&&(f=await Q());p(e,"permission-result",{type:d,result:f})}async function O(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}
async function Q(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}self.C.M(class extends self.N{constructor(e){super(e,"touch");E(this,"request-permission",d=>M(this,d))}});"use strict";
function R(e){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(d=>p(e,"sw-message",d.data))}
function S(e){e=e.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(e):screen.webkitLockOrientation?d=screen.webkitLockOrientation(e):screen.mozLockOrientation?d=screen.mozLockOrientation(e):screen.msLockOrientation&&(d=screen.msLockOrientation(e));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",
d)}}
self.C.M(class extends self.N{constructor(e){super(e,"browser");this.b="";F(this,[["get-initial-state",d=>{this.b=d.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>R(this)],
["alert",d=>this.ga(d)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",d=>this.la(d)],["vibrate",d=>{navigator.vibrate&&navigator.vibrate(d.pattern)}],["lock-orientation",d=>S(d)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(d){}}],["navigate",d=>{var f=d.type;if("back"===f)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===f)window.forward();else if("home"===f)window.home();else if("reload"===f)location.reload();else if("url"===f){f=d.url;var m=d.target;d=d.exportType;"windows-uwp"===d&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(f)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):"preview"===d?window.open(f,"_blank"):this.lc||(2===m?window.top.location=f:1===m?window.parent.location=f:window.location=f)}else"new-window"===f&&(f=d.url,m=d.tag,"windows-uwp"===d.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(f)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(f,"_system"):window.open(f,m))}],["request-fullscreen",
d=>{{const f={navigationUI:"auto"};d=d.navUI;1===d?f.navigationUI="hide":2===d&&(f.navigationUI="show");d=document.documentElement;d.requestFullscreen?d.requestFullscreen(f):d.mozRequestFullScreen?d.mozRequestFullScreen(f):d.msRequestFullscreen?d.msRequestFullscreen(f):d.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):d.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",d=>{location.hash=d.hash}]]);window.addEventListener("online",()=>{p(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{p(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{p(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{p(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",d=>{d.handled=!0;p(this,"backbutton")})}ga(e){alert(e.message)}la(e){e=e.isFocus;if("nwjs"===this.b){const d="nwjs"===this.b?nw.Window.get():null;e?d.focus():d.blur()}else e?window.focus():window.blur()}});"use strict";function T(e,d,f){U(e,d,URL.createObjectURL(new Blob([f.html],{type:"text/html"})));e.W=!0}
function U(e,d,f){d.src.startsWith("blob:")&&e.W&&URL.revokeObjectURL(d.src);d.src=f}
self.C.M(class extends self.$a{constructor(e){super(e,"iframe");this.W=!1;I(this,"navigate-url",(d,f)=>{U(this,d,f.url);this.W=!1});I(this,"display-html",(d,f)=>T(this,d,f))}Aa(e){const d=document.createElement("iframe");d.style.position="absolute";d.style.border="none";var f=navigator.userAgent;/iphone|ipad|ipod/i.test(f)&&(f=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(f),f=parseInt(f[f.length-1]),12>=f||isNaN(f))&&(d.setAttribute("noresize","noresize"),d.setAttribute("scrolling","no"));e.isVisible||
(d.style.display="none");e.id&&(d.id=e.id);e.allow&&(d.setAttribute("allow",e.allow),e.allow.includes("fullscreen")&&d.setAttribute("allowfullscreen",""));e.enableSandbox&&d.setAttribute("sandbox",e.sandbox);e.url?d.src=e.url:e.html&&T(this,d,e);return d}Ea(){}Ba(e){U(this,e,"");this.W=!1}});