'use strict';function u(g,d,c,k){g.f.ha(g.J,d,c,k,void 0)}function w(g,d,c,k){g.f.o?u(g,d,c,k):g.f.xb()._OnMessageFromDOM({type:"event",component:g.J,handler:d,dispatchOpts:k||null,data:c,responseId:null})}function B(g,d,c){g.f.a(g.J,d,c)}function F(g,d){for(const [c,k]of d)B(g,c,k)}window.T=class{constructor(g,d){this.f=g;this.J=d}Ga(){}};
window.mb=class{constructor(g,d){this.Ya=g;this.jc=d;this.D=-1;this.$=-Infinity;this.oc=()=>{this.D=-1;this.$=Date.now();this.K=!0;this.Ya();this.K=!1};this.Za=this.K=!1}};"use strict";function I(g,d){const c=d.elementId,k=g.G(c,d);g.h.set(c,k);d.isVisible||(k.style.display="none");d=g.ka(k);d.addEventListener("focus",()=>{L(g,"elem-focused",c)});d.addEventListener("blur",()=>{L(g,"elem-blurred",c)});g.X&&document.body.appendChild(k)}
function M(g,d,c){B(g,d,k=>{const n=g.h.get(k.elementId);return c(n,k)})}function L(g,d,c,k){k||(k={});k.elementId=c;u(g,d,k)}function N(g,d,c,k){k||(k={});k.elementId=c;w(g,d,k)}
window.S=class extends self.T{constructor(g,d){super(g,d);this.h=new Map;this.X=!0;F(this,[["create",c=>I(this,c)],["destroy",c=>{{c=c.elementId;const k=this.h.get(c);this.Ia(k);this.X&&k.parentElement.removeChild(k);this.h.delete(c)}}],["set-visible",c=>{this.X&&(this.h.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.X){var k=this.h.get(c.elementId);k.style.left=c.left+"px";k.style.top=c.top+"px";k.style.width=c.width+"px";k.style.height=c.height+"px";c=c.fontSize;
null!==c&&(k.style.fontSize=c+"em")}}],["update-state",c=>{{const k=this.h.get(c.elementId);this.m(k,c)}}],["focus",c=>this.ua(c)],["set-css-style",c=>{this.h.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.h.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.h.get(c.elementId).removeAttribute(c.name)}]]);M(this,"get-element",c=>c)}G(){throw Error("required override");}Ia(){}m(){throw Error("required override");}ka(g){return g}ua(g){const d=this.ka(this.h.get(g.elementId));
g.focus?d.focus():d.blur()}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let d=0;function c(f,a){const e=document.createElement("script");e.async=!1;"module"===a&&(e.type="module");return f.sc?new Promise(h=>{const m="c3_resolve_"+d;++d;self[m]=h;e.textContent=f.vc+`\n\nself["${m}"]();`;document.head.appendChild(e)}):new Promise((h,m)=>{e.onload=h;e.onerror=m;e.src=f;document.head.appendChild(e)})}let k=!1,n=!1;function x(){if(!k){try{new Worker("blob://",{get type(){n=!0}})}catch(f){}k=
!0}return n}let q=new Audio;const z={"audio/webm; codecs=opus":!!q.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!q.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!q.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!q.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!q.canPlayType("audio/mp4"),"audio/mpeg":!!q.canPlayType("audio/mpeg")};q=null;async function C(f){f=await J(f);return(new TextDecoder("utf-8")).decode(f)}function J(f){return new Promise((a,
e)=>{const h=new FileReader;h.onload=m=>a(m.target.result);h.onerror=m=>e(m);h.readAsArrayBuffer(f)})}const G=[];let A=0;window.RealFile=window.File;const D=[],v=new Map,E=new Map;let H=0;const K=[];self.runOnStartup=function(f){if("function"!==typeof f)throw Error("runOnStartup called without a function");K.push(f)};const b=new Set(["cordova","playable-ad","instant-games"]);window.l=class f{constructor(a){this.o=a.xc;this.M=null;this.c="";this.ca=a.uc;this.i=a.gb;this.P={};this.Aa=this.cb=null;this.Y=
[];this.L=this.g=this.Da=null;this.B=-1;this.nc=()=>this.Tb();this.bb=[];this.b=a.eb;!this.o||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.i||x())||(this.o=!1);b.has(this.b)&&this.o&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.o=!1);this.aa=this.j=null;"html5"!==this.b&&"playable-ad"!==this.b||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.a("runtime","cordova-fetch-local-file",e=>this.Fb(e));this.a("runtime","create-job-worker",()=>this.Gb());"cordova"===this.b?document.addEventListener("deviceready",()=>this.Na(a)):this.Na(a)}Ja(){return g&&"cordova"===this.b}ga(){return g&&b.has(this.b)||navigator.standalone}async Na(a){if("playable-ad"===this.b){this.j=self.c3_base64files;this.aa={};await this.sb();for(let h=0,m=a.F.length;h<m;++h){var e=a.F[h].toLowerCase();this.aa.hasOwnProperty(e)?a.F[h]={sc:!0,vc:this.aa[e]}:this.j.hasOwnProperty(e)&&
(a.F[h]=URL.createObjectURL(this.j[e]))}}a.pc?this.c=a.pc:(e=location.origin,this.c=("null"===e?"file:///":e)+location.pathname,e=this.c.lastIndexOf("/"),-1!==e&&(this.c=this.c.substr(0,e+1)));a.zc&&(this.P=a.zc);e=new MessageChannel;this.M=e.port1;this.M.onmessage=h=>this._OnMessageFromRuntime(h.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(h=>this.Qb(h));this.L=new self.kb(this);await O(this.L);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&
window.AndroidFullScreen.immersiveMode();this.o?await this.zb(a,e.port2):await this.yb(a,e.port2)}ma(a){a=this.P.hasOwnProperty(a)?this.P[a]:a.endsWith("/workermain.js")&&this.P.hasOwnProperty("workermain.js")?this.P["workermain.js"]:"playable-ad"===this.b&&this.j.hasOwnProperty(a.toLowerCase())?this.j[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async ea(a,e,h){if(a.startsWith("blob:"))return new Worker(a,h);if(this.Ja()&&"file:"===location.protocol)return a=await this.da(this.ca+
a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),h);a=new URL(a,e);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),h)}return new Worker(a,h)}v(){return Math.max(window.innerWidth,1)}u(){return Math.max(window.innerHeight,1)}La(a){var e=this.L;return{baseUrl:this.c,windowInnerWidth:this.v(),windowInnerHeight:this.u(),devicePixelRatio:window.devicePixelRatio,
isFullscreen:f.fa(),projectData:a.Fc,scriptsType:a.gb,previewImageBlobs:window.cr_previewImageBlobs||this.j,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Dc||"",exportType:a.eb,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Ec,jobScheduler:{inputPort:e.ya,outputPort:e.Ca,maxNumWorkers:e.lc},supportedAudioFormats:z,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ca+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||
this.ca+"opus.wasm.wasm",isiOSCordova:this.Ja(),isiOSWebView:this.ga(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async zb(a,e){var h=this.ma(a.yc);this.cb=await this.ea(h,this.c,{type:this.i,name:"Runtime"});this.g=document.createElement("canvas");this.g.style.display="none";h=this.g.transferControlToOffscreen();document.body.appendChild(this.g);window.c3canvas=this.g;this.cb.postMessage(Object.assign(this.La(a),{type:"init-runtime",isInWorker:!0,messagePort:e,canvas:h,workerDependencyScripts:a.Fa||
[],engineScripts:a.F,projectScripts:a.R,mainProjectScript:a.fb,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[e,h,...P(this.L)]);this.Y=D.map(m=>new m(this));this.Ka();self.c3_callFunction=(m,p)=>this.Da.Ab(m,p);"preview"===this.b&&(self.goToLastErrorScript=()=>this.ha("runtime","go-to-last-error-script"))}async yb(a,e){this.g=document.createElement("canvas");this.g.style.display="none";document.body.appendChild(this.g);window.c3canvas=this.g;this.Y=D.map(p=>new p(this));this.Ka();var h=a.F.map(p=>
"string"===typeof p?(new URL(p,this.c)).toString():p);Array.isArray(a.Fa)&&h.unshift(...a.Fa);h=await Promise.all(h.map(p=>this.oa(p,this.i)));await Promise.all(h.map(p=>c(p,this.i)));const m=self.C3_ProjectScriptsStatus;if("module"===this.i){h=a.fb;const p=a.R;for(let [t,r]of p)if(r||(r=t),t===h)try{r=await this.oa(r,this.i),await c(r,this.i),"preview"!==this.b||m[t]||this.Ta(t,"main script did not run to completion")}catch(y){this.Ta(t,y)}else if("scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r=
await this.oa(r,this.i),await c(r,this.i)}else if(a.R&&0<a.R.length)try{if(await Promise.all(a.R.map(p=>c(p[1],this.i))),Object.values(m).some(p=>!p)){self.setTimeout(()=>this.Ua(m),100);return}}catch(p){console.error("[Preview] Error loading project scripts: ",p);self.setTimeout(()=>this.Ua(m),100);return}"preview"===this.b&&"object"!==typeof self.Ac.Bc?(this.I(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(a=Object.assign(this.La(a),{isInWorker:!1,messagePort:e,canvas:this.g,runOnStartupFunctions:K}),this.Pa(),this.Aa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Aa,a))}Ua(a){this.I();a=`Failed to load project script '${Object.entries(a).filter(e=>!e[1]).map(e=>e[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}Ta(a,e){this.I();console.error(`[Preview] Failed to load project main script (${a}): `,e);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Pa(){this.I()}I(){const a=
window.qc;a&&(a.parentElement.removeChild(a),window.qc=null)}async Gb(){const a=await Q(this.L);return{outputPort:a,transferables:[a]}}xb(){if(this.o)throw Error("not available in worker mode");return this.Aa}ha(a,e,h,m,p){this.M.postMessage({type:"event",component:a,handler:e,dispatchOpts:m||null,data:h,responseId:null},p)}lb(a,e){const h=H++,m=new Promise((p,t)=>{E.set(h,{resolve:p,reject:t})});this.M.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:e,responseId:h},
void 0);return m}["_OnMessageFromRuntime"](a){const e=a.type;if("event"===e)return this.Lb(a);if("result"===e)this.Xb(a);else if("runtime-ready"===e)this.Yb();else if("alert-error"===e)this.I(),alert(a.message);else if("creating-runtime"===e)this.Pa();else throw Error(`unknown message '${e}'`);}Lb(a){const e=a.component,h=a.handler,m=a.data,p=a.responseId;if(a=v.get(e))if(a=a.get(h)){var t=null;try{t=a(m)}catch(r){console.error(`Exception in '${e}' handler '${h}':`,r);null!==p&&this.V(p,!1,""+r);
return}if(null===p)return t;t&&t.then?t.then(r=>this.V(p,!0,r)).catch(r=>{console.error(`Rejection from '${e}' handler '${h}':`,r);this.V(p,!1,""+r)}):this.V(p,!0,t)}else console.warn(`[DOM] No handler '${h}' for component '${e}'`);else console.warn(`[DOM] No event handlers for component '${e}'`)}V(a,e,h){let m;h&&h.transferables&&(m=h.transferables);this.M.postMessage({type:"result",responseId:a,isOk:e,result:h},m)}Xb(a){const e=a.responseId,h=a.isOk;a=a.result;const m=E.get(e);h?m.resolve(a):m.reject(a);
E.delete(e)}a(a,e,h){let m=v.get(a);m||(m=new Map,v.set(a,m));if(m.has(e))throw Error(`[DOM] Component '${a}' already has handler '${e}'`);m.set(e,h)}static s(a){if(D.includes(a))throw Error("DOM handler already added");D.push(a)}Ka(){for(const a of this.Y)if("runtime"===a.J){this.Da=a;return}throw Error("cannot find runtime DOM handler");}Qb(a){this.ha("debugger","message",a)}Yb(){for(const a of this.Y)a.Ga()}static fa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Va(){-1===
this.B&&this.bb.length&&(this.B=requestAnimationFrame(this.nc))}qb(){-1!==this.B&&(cancelAnimationFrame(this.B),this.B=-1)}Tb(){this.B=-1;for(const a of this.bb)a();this.Va()}wa(){this.Da.wa()}ib(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}jb(a){return!this.ib(a)}async oa(a,e){return"cordova"===this.b&&"module"===e&&(a.startsWith("file:")||"file:"===location.protocol&&this.jb(a))?(a.startsWith(this.c)&&(a=a.substr(this.c.length)),a=await this.da(a),URL.createObjectURL(new Blob([a],
{type:"application/javascript"}))):a}async Fb(a){const e=a.filename;switch(a.as){case "text":return await this.hb(e);case "buffer":return await this.da(e);default:throw Error("unsupported type");}}Ha(a){const e=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((h,m)=>{window.resolveLocalFileSystemURL(e,p=>{p.file(h,m)},m)})}async hb(a){a=await this.Ha(a);return await C(a)}ia(){if(G.length&&!(8<=A)){A++;var a=G.shift();this.tb(a.filename,a.wc,a.rc)}}da(a){return new Promise((e,
h)=>{G.push({filename:a,wc:m=>{A--;this.ia();e(m)},rc:m=>{A--;this.ia();h(m)}});this.ia()})}async tb(a,e,h){try{const m=await this.Ha(a),p=await J(m);e(p)}catch(m){h(m)}}async sb(){const a=[];for(const [e,h]of Object.entries(this.j))a.push(this.rb(e,h));await Promise.all(a)}async rb(a,e){if("object"===typeof e)this.j[a]=new Blob([e.str],{type:e.type}),this.aa[a]=e.str;else{let h=await this.wb(e);h||(h=this.ub(e));this.j[a]=h}}async wb(a){try{return await (await fetch(a)).blob()}catch(e){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
e),null}}ub(a){a=this.ec(a);return this.pb(a.data,a.tc)}ec(a){var e=a.indexOf(",");if(0>e)throw new URIError("expected comma in data: uri");var h=a.substring(e+1);e=a.substring(5,e).split(";");a=e[0]||"";const m=e[2];h="base64"===e[1]||"base64"===m?atob(h):decodeURIComponent(h);return{tc:a,data:h}}pb(a,e){var h=a.length;let m=h>>2,p=new Uint8Array(h),t=new Uint32Array(p.buffer,0,m),r,y;for(y=r=0;r<m;++r)t[r]=a.charCodeAt(y++)|a.charCodeAt(y++)<<8|a.charCodeAt(y++)<<16|a.charCodeAt(y++)<<24;for(h&=
3;h--;)p[y]=a.charCodeAt(y),++y;return new Blob([p],{type:e})}}}"use strict";
{const g=self.l;function d(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const c=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),k={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},n={dispatchUserScriptEvent:!0},x={dispatchRuntimeEvent:!0};function q(b){return new Promise((f,a)=>{const e=document.createElement("link");e.onload=()=>f(e);e.onerror=h=>a(h);e.rel=
"stylesheet";e.href=b;document.head.appendChild(e)})}function z(b){return new Promise((f,a)=>{const e=new Image;e.onload=()=>f(e);e.onerror=h=>a(h);e.src=b})}async function C(b){b=URL.createObjectURL(b);try{return await z(b)}finally{URL.revokeObjectURL(b)}}function J(b){return new Promise((f,a)=>{let e=new FileReader;e.onload=h=>f(h.target.result);e.onerror=h=>a(h);e.readAsText(b)})}async function G(b,f,a){if(!/firefox/i.test(navigator.userAgent))return await C(b);var e=await J(b);e=(new DOMParser).parseFromString(e,
"image/svg+xml");const h=e.documentElement;if(h.hasAttribute("width")&&h.hasAttribute("height")){const m=h.getAttribute("width"),p=h.getAttribute("height");if(!m.includes("%")&&!p.includes("%"))return await C(b)}h.setAttribute("width",f+"px");h.setAttribute("height",a+"px");e=(new XMLSerializer).serializeToString(e);b=new Blob([e],{type:"image/svg+xml"});return await C(b)}function A(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const D=new Set(["canvas",
"body","html"]);function v(b){D.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function E(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await C(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const f=b.getBoundingClientRect();document.body.removeChild(b);return[f.width,f.height]}};self.C3_RasterSvgImageBlob=async function(b,
f,a,e,h){b=await G(b,f,a);const m=document.createElement("canvas");m.width=e;m.height=h;m.getContext("2d").drawImage(b,0,0,f,a);return m};let H=!1;document.addEventListener("pause",()=>H=!0);document.addEventListener("resume",()=>H=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}g.s(class extends self.T{constructor(b){super(b,"runtime");this.$a=!0;this.C=-1;this.Ea="any";this.Wa=this.Xa=!1;this.za=this.O=this.A=null;b.a("canvas","update-size",e=>this.cc(e));
b.a("runtime","invoke-download",e=>this.Ob(e));b.a("runtime","raster-svg-image",e=>this.Ub(e));b.a("runtime","get-svg-image-size",e=>this.Mb(e));b.a("runtime","set-target-orientation",e=>this.bc(e));b.a("runtime","register-sw",()=>this.Vb());b.a("runtime","post-to-debugger",e=>this.Ra(e));b.a("runtime","go-to-script",e=>this.Ra(e));b.a("runtime","before-start-ticking",()=>this.Db());b.a("runtime","debug-highlight",e=>this.Hb(e));b.a("runtime","enable-device-orientation",()=>this.ob());b.a("runtime",
"enable-device-motion",()=>this.nb());b.a("runtime","add-stylesheet",e=>this.Cb(e));b.a("runtime","alert",e=>this.pa(e));b.a("runtime","hide-cordova-splash",()=>this.Nb());const f=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",e=>{const h=e.target;f.has(h.tagName.toLowerCase())||A(h)||e.preventDefault()});const a=b.g;window.addEventListener("selectstart",v);window.addEventListener("gesturehold",v);a.addEventListener("selectstart",v);a.addEventListener("gesturehold",
v);window.addEventListener("touchstart",v,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",v,{passive:!1}),a.addEventListener("pointerdown",v)):a.addEventListener("touchstart",v);this.N=0;window.addEventListener("mousedown",e=>{1===e.button&&e.preventDefault()});window.addEventListener("mousewheel",E,{passive:!1});window.addEventListener("wheel",E,{passive:!1});window.addEventListener("resize",()=>this.dc());window.addEventListener("fullscreenchange",()=>this.qa());
window.addEventListener("webkitfullscreenchange",()=>this.qa());window.addEventListener("mozfullscreenchange",()=>this.qa());window.addEventListener("fullscreenerror",e=>this.ra(e));window.addEventListener("webkitfullscreenerror",e=>this.ra(e));window.addEventListener("mozfullscreenerror",e=>this.ra(e));b.ga()&&window.addEventListener("focusout",()=>{{const m=document.activeElement;if(m){var e=m.tagName.toLowerCase();var h=new Set("email number password search tel text url".split(" "));e="textarea"===
e?!0:"input"===e?h.has(m.type.toLowerCase()||"text"):A(m)}else e=!1}e||(document.scrollingElement.scrollTop=0)});this.Ba=new Set;this.mc=new WeakSet;this.kc=!1}Db(){"cordova"===this.f.b?(document.addEventListener("pause",()=>this.va(!0)),document.addEventListener("resume",()=>this.va(!1))):document.addEventListener("visibilitychange",()=>this.va(document.hidden));return{isSuspended:!(!document.hidden&&!H)}}Ga(){window.addEventListener("focus",()=>this.W("window-focus"));window.addEventListener("blur",
()=>{this.W("window-blur",{parentHasFocus:K()});this.N=0});window.addEventListener("keydown",f=>this.Qa("keydown",f));window.addEventListener("keyup",f=>this.Qa("keyup",f));window.addEventListener("dblclick",f=>this.sa("dblclick",f,k));window.addEventListener("wheel",f=>this.Rb(f));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",f=>{this.na(f);this.H("pointerdown",f)}),this.f.o&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.O=new self.mb(()=>this.vb(),
5),this.O.Za=!0,window.addEventListener("pointerrawupdate",f=>this.Sb(f))):window.addEventListener("pointermove",f=>this.H("pointermove",f)),window.addEventListener("pointerup",f=>this.H("pointerup",f)),window.addEventListener("pointercancel",f=>this.H("pointercancel",f))):(window.addEventListener("mousedown",f=>{this.na(f);this.ta("pointerdown",f)}),window.addEventListener("mousemove",f=>this.ta("pointermove",f)),window.addEventListener("mouseup",f=>this.ta("pointerup",f)),window.addEventListener("touchstart",
f=>{this.na(f);this.U("pointerdown",f)}),window.addEventListener("touchmove",f=>this.U("pointermove",f)),window.addEventListener("touchend",f=>this.U("pointerup",f)),window.addEventListener("touchcancel",f=>this.U("pointercancel",f)));const b=()=>this.wa();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}W(b,f){u(this,b,f||null,x)}v(){return this.f.v()}u(){return this.f.u()}dc(){const b=
this.v(),f=this.u();this.W("window-resize",{innerWidth:b,innerHeight:f,devicePixelRatio:window.devicePixelRatio});this.f.ga()&&(-1!==this.C&&clearTimeout(this.C),this.Sa(b,f,0))}fc(b,f,a){-1!==this.C&&clearTimeout(this.C);this.C=setTimeout(()=>this.Sa(b,f,a),48)}Sa(b,f,a){const e=this.v(),h=this.u();this.C=-1;e!=b||h!=f?this.W("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio}):10>a&&this.fc(e,h,a+1)}bc(b){this.Ea=b.targetOrientation}hc(){const b=this.Ea;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(b).catch(f=>console.warn("[Construct 3] Failed to lock orientation: ",f));else try{let f=!1;screen.lockOrientation?f=screen.lockOrientation(b):screen.webkitLockOrientation?f=screen.webkitLockOrientation(b):screen.mozLockOrientation?f=screen.mozLockOrientation(b):screen.msLockOrientation&&(f=screen.msLockOrientation(b));f||console.warn("[Construct 3] Failed to lock orientation")}catch(f){console.warn("[Construct 3] Failed to lock orientation: ",f)}}qa(){const b=
g.fa();b&&"any"!==this.Ea&&this.hc();u(this,"fullscreenchange",{isFullscreen:b,innerWidth:this.v(),innerHeight:this.u()})}ra(b){console.warn("[Construct 3] Fullscreen request failed: ",b);u(this,"fullscreenerror",{isFullscreen:g.fa(),innerWidth:this.v(),innerHeight:this.u()})}va(b){b?this.f.qb():this.f.Va();u(this,"visibilitychange",{hidden:b})}Qa(b,f){"Backspace"===f.key&&v(f);const a=c.get(f.code)||f.code;w(this,b,{code:a,key:f.key,which:f.which,repeat:f.repeat,altKey:f.altKey,ctrlKey:f.ctrlKey,
metaKey:f.metaKey,shiftKey:f.shiftKey,timeStamp:f.timeStamp},k)}Rb(b){u(this,"wheel",{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},k)}sa(b,f,a){d(f)||w(this,b,{button:f.button,buttons:f.buttons,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,timeStamp:f.timeStamp},a)}ta(b,f){if(!d(f)){var a=this.N;"pointerdown"===b&&0!==a?b="pointermove":"pointerup"===b&&0!==f.buttons&&(b=
"pointermove");w(this,b,{pointerId:1,pointerType:"mouse",button:f.button,buttons:f.buttons,lastButtons:a,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:f.timeStamp},k);this.N=f.buttons;this.sa(f.type,f,n)}}H(b,f){if(this.O&&"pointermove"!==b){var a=this.O;a.K||(-1!==a.D&&(self.clearTimeout(a.D),a.D=-1),a.$=Date.now())}a=0;"mouse"===f.pointerType&&(a=this.N);w(this,b,{pointerId:f.pointerId,pointerType:f.pointerType,
button:f.button,buttons:f.buttons,lastButtons:a,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,width:f.width||0,height:f.height||0,pressure:f.pressure||0,tangentialPressure:f.tangentialPressure||0,tiltX:f.tiltX||0,tiltY:f.tiltY||0,twist:f.twist||0,timeStamp:f.timeStamp},k);"mouse"===f.pointerType&&(a="mousemove","pointerdown"===b?a="mousedown":"pointerup"===b&&(a="mouseup"),this.sa(a,f,n),this.N=f.buttons)}Sb(b){this.za=b;b=this.O;if(-1===b.D){var f=Date.now(),a=f-b.$,e=b.jc;a>=e&&
b.Za?(b.$=f,b.K=!0,b.Ya(),b.K=!1):b.D=self.setTimeout(b.oc,Math.max(e-a,4))}}vb(){this.H("pointermove",this.za);this.za=null}U(b,f){for(let a=0,e=f.changedTouches.length;a<e;++a){const h=f.changedTouches[a];w(this,b,{pointerId:h.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:2*(h.radiusX||h.webkitRadiusX||0),height:2*(h.radiusY||h.webkitRadiusY||0),pressure:h.force||h.webkitForce||0,tangentialPressure:0,tiltX:0,
tiltY:0,twist:h.rotationAngle||0,timeStamp:f.timeStamp},k)}}na(b){window!==window.top&&window.focus();this.Oa(b.target)&&document.activeElement&&!this.Oa(document.activeElement)&&document.activeElement.blur()}Oa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}ob(){this.Xa||(this.Xa=!0,window.addEventListener("deviceorientation",b=>this.Jb(b)),window.addEventListener("deviceorientationabsolute",b=>this.Kb(b)))}nb(){this.Wa||(this.Wa=!0,window.addEventListener("devicemotion",
b=>this.Ib(b)))}Jb(b){u(this,"deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},k)}Kb(b){u(this,"deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},k)}Ib(b){let f=null;var a=b.acceleration;a&&(f={x:a.x||0,y:a.y||0,z:a.z||0});a=null;var e=b.accelerationIncludingGravity;e&&(a={x:e.x||
0,y:e.y||0,z:e.z||0});e=null;const h=b.rotationRate;h&&(e={alpha:h.alpha||0,beta:h.beta||0,gamma:h.gamma||0});u(this,"devicemotion",{acceleration:f,accelerationIncludingGravity:a,rotationRate:e,interval:b.interval,timeStamp:b.timeStamp},k)}cc(b){const f=this.f.g;f.style.width=b.styleWidth+"px";f.style.height=b.styleHeight+"px";f.style.marginLeft=b.marginLeft+"px";f.style.marginTop=b.marginTop+"px";this.$a&&(f.style.display="",this.$a=!1)}Ob(b){const f=b.url;b=b.filename;const a=document.createElement("a"),
e=document.body;a.textContent=b;a.href=f;a.download=b;e.appendChild(a);a.click();e.removeChild(a)}async Ub(b){var f=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);f=f?await createImageBitmap(b,f):await createImageBitmap(b);return{imageBitmap:f,transferables:[f]}}async Mb(b){return await self.C3_GetSvgImageSize(b.blob)}async Cb(b){await q(b.url)}wa(){var b=[...this.Ba];this.Ba.clear();if(!this.kc)for(const f of b)(b=f.play())&&
b.catch(()=>{this.mc.has(f)||this.Ba.add(f)})}Nb(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}Hb(b){if(b.show){this.A||(this.A=document.createElement("div"),this.A.id="inspectOutline",document.body.appendChild(this.A));var f=this.A;f.style.display="";f.style.left=b.left-1+"px";f.style.top=b.top-1+"px";f.style.width=b.width+2+"px";f.style.height=b.height+2+"px";f.textContent=b.name}else this.A&&(this.A.style.display="none")}Vb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ra(b){window.c3_postToMessagePort&&
(b.from="runtime",window.c3_postToMessagePort(b))}Ab(b,f){return this.f.lb(this.J,{name:b,params:f})}pa(b){alert(b.message)}})}"use strict";async function O(g){if(g.ic)throw Error("already initialised");g.ic=!0;var d=g.ba.ma("dispatchworker.js");g.xa=await g.ba.ea(d,g.c,{name:"DispatchWorker"});d=new MessageChannel;g.ya=d.port1;g.xa.postMessage({type:"_init","in-port":d.port2},[d.port2]);g.Ca=await Q(g)}function P(g){return[g.ya,g.Ca]}
async function Q(g){const d=g.ab.length;var c=g.ba.ma("jobworker.js");c=await g.ba.ea(c,g.c,{name:"JobWorker"+d});const k=new MessageChannel,n=new MessageChannel;g.xa.postMessage({type:"_addJobWorker",port:k.port1},[k.port1]);c.postMessage({type:"init",number:d,"dispatch-port":k.port2,"output-port":n.port2},[k.port2,n.port2]);g.ab.push(c);return n.port1}
self.kb=class{constructor(g){this.ba=g;this.c=g.c;this.c="preview"===g.b?this.c+"c3/workers/":this.c+g.ca;this.lc=Math.min(navigator.hardwareConcurrency||2,16);this.xa=null;this.ab=[];this.Ca=this.ya=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.l({xc:!0,yc:"workermain.js",F:["scripts/c3runtime.js"],R:[],fb:"",gb:"module",uc:"scripts/",Fa:[],eb:"html5"}));"use strict";
async function R(g,d){d=d.type;let c=!0;0===d?c=await U():1===d&&(c=await V());u(g,"permission-result",{type:d,result:c})}async function U(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function V(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.l.s(class extends self.T{constructor(g){super(g,"touch");B(this,"request-permission",d=>R(this,d))}});"use strict";
function W(g){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(d=>u(g,"sw-message",d.data))}
function X(g){g=g.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(g).catch(d=>console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(g):screen.webkitLockOrientation?d=screen.webkitLockOrientation(g):screen.mozLockOrientation?d=screen.mozLockOrientation(g):screen.msLockOrientation&&(d=screen.msLockOrientation(g));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",
d)}}
self.l.s(class extends self.T{constructor(g){super(g,"browser");this.b="";F(this,[["get-initial-state",d=>{this.b=d.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>W(this)],
["alert",d=>this.pa(d)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",d=>this.ua(d)],["vibrate",d=>{navigator.vibrate&&navigator.vibrate(d.pattern)}],["lock-orientation",d=>X(d)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(d){}}],["navigate",d=>{var c=d.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===c)window.forward();else if("home"===c)window.home();else if("reload"===c)location.reload();else if("url"===c){c=d.url;var k=d.target;d=d.exportType;"windows-uwp"===d&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(c)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===d||"windows-webview2"===d?window.open(c,"_blank"):this.Cc||(2===k?window.top.location=c:1===k?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=d.url,k=d.tag,"windows-uwp"===d.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(c)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,k))}],
["request-fullscreen",d=>{{const c={navigationUI:"auto"};d=d.navUI;1===d?c.navigationUI="hide":2===d&&(c.navigationUI="show");d=document.documentElement;d.requestFullscreen?d.requestFullscreen(c):d.mozRequestFullScreen?d.mozRequestFullScreen(c):d.msRequestFullscreen?d.msRequestFullscreen(c):d.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?d.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):d.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?
document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",d=>{location.hash=d.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});
document.addEventListener("backbutton",()=>{u(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",d=>{d.handled=!0;u(this,"backbutton")})}pa(g){alert(g.message)}ua(g){g=g.isFocus;if("nwjs"===this.b){const d="nwjs"===this.b?nw.Window.get():null;g?d.focus():d.blur()}else g?window.focus():window.blur()}});"use strict";function Y(g,d,c){Z(g,d,URL.createObjectURL(new Blob([c.html],{type:"text/html"})));g.Z=!0}
function Z(g,d,c){d.src.startsWith("blob:")&&g.Z&&URL.revokeObjectURL(d.src);d.src=c}
self.l.s(class extends self.S{constructor(g){super(g,"iframe");this.Z=!1;M(this,"navigate-url",(d,c)=>{Z(this,d,c.url);this.Z=!1});M(this,"display-html",(d,c)=>Y(this,d,c))}G(g,d){g=document.createElement("iframe");g.style.position="absolute";g.style.border="none";var c=navigator.userAgent;/iphone|ipad|ipod/i.test(c)&&(c=/(iphone\s+os|ipad[^)]*os)\s+([0-9_]+)/i.exec(c),c=parseInt(c[c.length-1]),12>=c||isNaN(c))&&(g.setAttribute("noresize","noresize"),g.setAttribute("scrolling","no"));d.isVisible||
(g.style.display="none");d.id&&(g.id=d.id);d.allow&&(g.setAttribute("allow",d.allow),d.allow.includes("fullscreen")&&g.setAttribute("allowfullscreen",""));d.enableSandbox&&g.setAttribute("sandbox",d.sandbox);d.url?g.src=d.url:d.html&&Y(this,g,d);return g}m(){}Ia(g){Z(this,g,"");this.Z=!1}});"use strict";
{function g(d){d.stopPropagation()}self.l.s(class extends self.S{constructor(d){super(d,"button")}G(d,c){const k=document.createElement("input");var n=k;c.isCheckbox?(k.type="checkbox",n=document.createElement("label"),n.appendChild(k),n.appendChild(document.createTextNode("")),n.style.fontFamily="sans-serif",n.style.userSelect="none",n.style.webkitUserSelect="none",n.style.display="inline-block",n.style.color="black"):k.type="button";n.style.position="absolute";n.addEventListener("touchstart",g);
n.addEventListener("touchmove",g);n.addEventListener("touchend",g);n.addEventListener("mousedown",g);n.addEventListener("mouseup",g);n.addEventListener("keydown",g);n.addEventListener("keyup",g);k.addEventListener("click",()=>N(this,"click",d,{isChecked:k.checked}));c.id&&(k.id=c.id);this.m(n,c);return n}Ma(d){return"input"===d.tagName.toLowerCase()?d:d.firstChild}ka(d){return this.Ma(d)}m(d,c){const k=this.Ma(d);k.checked=c.isChecked;k.disabled=!c.isEnabled;d.title=c.title;d===k?k.value=c.text:d.lastChild.textContent=
c.text}})}"use strict";
{function g(c){c.stopPropagation()}function d(c){13!==c.which&&27!==c.which&&c.stopPropagation()}self.l.s(class extends self.S{constructor(c){super(c,"text-input");M(this,"scroll-to-bottom",k=>this.Zb(k))}G(c,k){let n;const x=k.type;"textarea"===x?(n=document.createElement("textarea"),n.style.resize="none"):(n=document.createElement("input"),n.type=x);n.style.position="absolute";n.autocomplete="off";n.addEventListener("touchstart",g);n.addEventListener("touchmove",g);n.addEventListener("touchend",g);
n.addEventListener("mousedown",g);n.addEventListener("mouseup",g);n.addEventListener("keydown",d);n.addEventListener("keyup",d);n.addEventListener("click",q=>{q.stopPropagation();N(this,"click",c)});n.addEventListener("dblclick",q=>{q.stopPropagation();N(this,"dblclick",c)});n.addEventListener("input",()=>L(this,"change",c,{text:n.value}));k.id&&(n.id=k.id);this.m(n,k);return n}m(c,k){c.value=k.text;c.placeholder=k.placeholder;c.title=k.title;c.disabled=!k.isEnabled;c.readOnly=k.isReadOnly;c.spellcheck=
k.spellCheck;k=k.maxLength;0>k?c.removeAttribute("maxlength"):c.setAttribute("maxlength",k)}Zb(c){c.scrollTop=c.scrollHeight}})}"use strict";
{function g(d){d.stopPropagation()}self.l.s(class extends self.S{constructor(d){super(d,"list");M(this,"set-selected-index",(c,k)=>this.ac(c,k.selectedIndex));M(this,"add-item",(c,k)=>this.Bb(c,k));M(this,"remove-item",(c,k)=>this.Wb(c,k));M(this,"set-item",(c,k)=>this.$b(c,k));M(this,"clear",c=>this.Eb(c));M(this,"load-state",(c,k)=>this.Pb(c,k))}G(d,c){const k=c.isDropdown,n=c.isMultiSelect,x=c.items,q=document.createElement("select");q.style.position="absolute";q.style.userSelect="none";q.style.webkitUserSelect=
"none";q.multiple=n;k||(q.size=2);for(const z of x)q.add(this.ja(z));q.addEventListener("touchstart",g);q.addEventListener("touchmove",g);q.addEventListener("touchend",g);q.addEventListener("mousedown",g);q.addEventListener("mouseup",g);q.addEventListener("click",z=>{z.stopPropagation();N(this,"click",d,this.la(q))});q.addEventListener("dblclick",z=>{z.stopPropagation();N(this,"dblclick",d,this.la(q))});q.addEventListener("change",()=>L(this,"change",d,this.la(q)));c.id&&(q.id=c.id);this.m(q,c);return q}ja(d){const c=
document.createElement("option");c.text=d;return c}la(d){const c=d.selectedIndex,k=[];for(let n=0,x=d.length;n<x;++n)d.options[n].selected&&k.push(n);return{selectedIndex:c,selectedIndices:k}}m(d,c){d.title=c.title;d.disabled=!c.isEnabled;d.multiple=!!c.isMultiSelect}ac(d,c){d.selectedIndex=c}Bb(d,c){const k=c.index;c=this.ja(c.text);0>k?d.add(c):d.add(c,k)}Wb(d,c){d.remove(c.index)}$b(d,c){d.options[c.index].text=c.text}Eb(d){d.innerHTML=""}Pb(d,c){d.innerHTML="";for(const k of c.items)d.add(this.ja(k));
d.selectedIndex=c.selectedIndex;for(const k of c.selectedIndices)if(c=d.options[k])c.selected=!0}})};
